services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-tlaucer-server
    ports:
      - "1350:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "false"
      TYPE: "PAPER"
      VERSION: "latest"
      MEMORY: "4096M"
      JVM_OPTS: "-Xmx4096M -Xms2048M"
      DIFFICULTY: "2"
      GAMEMODE: "0"
      PVP: "true"
      ALLOW_FLIGHT: "false"
      MAX_PLAYERS: "20"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "mcusiman123"
      RCON_PORT: "25575"
    volumes:
      - /home/ghozy/Server-Tlaucer:/data
    restart: unless-stopped
